baseURL = 'https://rmmod.com/'
languageCode = 'en-us'
title = 'Guanlan Dai'
theme = 'LoveIt'

enableEmoji = true

[params]
  defaultTheme = "auto"
  dateFormat = "2006-01-02"
  rss = true

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"

    [params.header.title]
      name = "Guanlan Dai"

  [params.footer]
    enable = true
    hugo = false
    custom = "Guanlan Dai | CC BY-NC 4.0"
    copyright = true 
    author = true 
    since = 2009

  [params.social]
    RSS = true

  [params.page]
    [params.page.library]
      [params.page.library.css]
        # 添加代码高亮样式文件
        codeHighlight = "css/_code-highlight.scss"

[menu]
  [[menu.main]]
    weight = 1
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    weight = 2
    identifier = "about"
    name = "About"
    url = "/about/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # LoveIt 主题要求必须设置为 false
    noClasses = false
